language: node_js
node_js:
  - "8.4.0"
cache:
  directories:
  - node_modules
script:
  - npm install
  - npm run build
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
